name: Test Composer Dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-composer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Specify the PHP version you want to use
        tools: composer

    - name: Validate composer.json
      run: composer validate --strict

    - name: Update composer.json
      run: composer update --no-interaction --prefer-dist

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Update dependencies
      run: composer update --no-interaction --prefer-dist

    - name: Run additional tests (optional)
      run: |
        # Run any additional tests or scripts here
        # Example: vendor/bin/phpunit
